### ISSUE TITLE
Authentication failing in sample app

### ISSUE THREAD

**Issue by justincy** [york-solutions/fs-php-lite#6]
Migrated from https://github.com/FamilySearch/gedcomx-php/issues/68

@ewugoat7 

> Am trying the familysearch API developed for PHP. when I authenticate,
> everything was successful.
> 
> Here is the issues am having. on the success page.
> 
> when i click on "Is User Authenticated? button", it will display error User not authenticated.
> 2.)When I click on current user button on the left side, it displays this error
> status	401 Unauthorized
> code	401
> message	Unauthorized
> the same issue is applicable with the rest like clicking
> clicking on "Current Person" etc..
> Those it means that php session is not well established
> after I have successfully authenticated.
> why am I getting those errors above......
> This is urgent to enable me submit my apps. Thanks

**Comment by justincy** [comment]
@ewugoat7 It works properly for me. It's hard to know what's happening for you. Are you sure that authentication is working? Perhaps you could copy and paste the output of the authentication response.

**Comment by deboyisgood** [comment]
please sir, I sent you a link to the web site so that you can test the app and see the issue.
please see your email (justincyork at gmail.
[dot]com)

Thanks

**Comment by deboyisgood** [comment]
Hello sir, I have sent you a link to the working app with my login
credentials at
justincyork at gmail[dot]com

Thanks

**Comment by justincy** [comment]
The problem is that you changed the redirect URI. After logging in with FamilySearch the user needs to be returned to a page that handles the redirect response. In the sample app that page is `oauthResponse.php`. If you want the user to end up somewhere else then do a redirect at the end of `oauthResponse.php`

**Comment by deboyisgood** [comment]
Thanks
